listen: :25565
servers:
  localhost: "117.173.88.106:25577"
default_info:
  version:
    name: Innocent Minecraft Server
    protocol: 0
  players:
    max: 0
    online: 0
    sample: []
  description:
    text: Not a minecraft server
